print("---------------------CENTRAL DE CONVERSÃO---------------------")
temp = float(input("Informe uma temperatura em Graus Celcius :"))
print("---------------------------------------------------------------------------------------------")
print("{:.2f}°C é o equivalente {:.2f} Fahrenheit".format(temp, ((temp * 9/5) + 32)))
print("---------------------------------------------------------------------------------------------")
