a = input("Digite algo:")
print("O tipo primitivo informado é: ",type(a))
print("Só tem espaços?: ", a.isspace())
print("É um número?:", a.isnumeric())
print("É alfanúmerico?:",a.isalpha())
print("Está em maiúsculas?:", a.isupper())
print("Está em minúsculas?:", a.islower())
