print("----------------------------------------------------------------")
nome = str(input("Informe seu nome completo: ")).strip()
("----------------------------------------------------------------")
print("Verificando se o seu nome possui 'Silva'")
n = nome.lower()
print("silva" in n)
("----------------------------------------------------------------")